[project]
org-name = "ballerina"
version = "2.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "cache"
    version = "2.0.0-SNAPSHOT"
    path = "../cache-native/build/libs/cache-native-2.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["cache"]
